// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dseciraaksejvuofxnge.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRzZWNpcmFha3NlanZ1b2Z4bmdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzMDU4NTcsImV4cCI6MjA4ODg4MTg1N30.NKtPyfZTXpbvSAkDKjNuyd6xhQiOEr3l0F5XCCw1djA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});